In [3]:
import numpy as np
from pysr import PySRRegressor, jl
import random
import pickle
import matplotlib.pyplot as plt
from collections import defaultdict
from sympy import *
import warnings
from itertools import permutations

warnings.filterwarnings("ignore")


Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython


In [4]:

def create_loss(signals, states):
    """
    Description: Create a custom loss function for the symbolic regression based on the number of signals and states.
    The function follows RSA's steps to turn a literal listener into a pragmatic speaker and then into a pragmatic listener, 
    while using the predicted formula as a utility function. 
    The loss function calculates the discrepancy using a multinomial loss.

    Parameters:
    signals: (int): Number of signals
    states: (int): Number of states
    """
    str1 = """function pragmatic_speaker_objective(tree, dataset::Dataset{T,L}, options) where {T,L}"""
    str2 = f"""
    # Matrix dimensions
    num_rows = {signals}
    num_cols = {states}
    matrix_size = num_rows * num_cols

    # Get predictions
    prediction, completion = eval_tree_array(tree, dataset.X, options)
    if !completion
        return L(Inf)  # Return a high loss if evaluation fails
    end

    # exp on the predictions
    prediction = exp.(prediction)

    # Normalize each column within each matrix
    pragmatic_speaker = Float64[]
    for i in 1:matrix_size:length(prediction)
        matrix = prediction[i:i + matrix_size - 1]
        
        # Normalize each column for current matrix
        for j in 1:num_cols
            column = matrix[j:num_cols:end]
            
            column_sum = sum(column)
            normalized_column = column_sum != 0 ? column / column_sum : column

            matrix[j:num_cols:end] .= normalized_column
        end
        
        append!(pragmatic_speaker, matrix)
    end

    pragmatic_listener = Float64[]
    for i in 1:matrix_size:length(pragmatic_speaker)
        matrix = pragmatic_speaker[i:i + matrix_size - 1]
        # Normalize each row for current matrix
        for j in 1:num_rows
            row = matrix[(j-1)*num_cols+1:j*num_cols]
            
            row_sum = sum(row)
            normalized_row = row_sum != 0 ? row / row_sum : row

            matrix[(j-1)*num_cols+1:j*num_cols] .= normalized_row
        end
        # Append the normalized matrix to the predictions list
        append!(pragmatic_listener, matrix)
    end

    # calculates loss for each row then add to total loss
    total_loss = 0.0
    for i in 1:num_cols:length(pragmatic_listener)
        row_start = i
        row_end = row_start + num_cols -1

        predicted_row = pragmatic_listener[row_start:row_end]
        target_row = dataset.y[row_start:row_end]
        
        # Multinomial loss for the row
        row_loss = -sum(target_row .* log.(predicted_row))
        total_loss += row_loss
    end

    # average loss
    avg_loss = total_loss / (length(pragmatic_listener) / num_cols)
    
    return avg_loss
end
"""
    return str1+str2

"""
multinomial loss doesnt work yet:
        n = sum(target_row)
        multinomial = prod(1:n) / prod([prod(1:c) for c in predicted_row]) # * prod(target_row .^ predicted_row)
        total_loss += -log(multinomial)
"""


def create_language_tables(n_signals, n_states, e):
    """
    Description:
    This function generates all possible language tables for a given language size.
    The language size is defined by the amount of signals and the amount of states.
    
    Parameters:
    n_signals (int): The amount of signals in the language table.
    n_states (int): The amount of states in the language table.
    e (float): The epsilon value to add to the language tables.
    """
    possible_tables = np.array(np.meshgrid(*[[0, 1]] * (n_signals * n_states))).T.reshape(-1, n_signals, n_states)
    true_tables = np.array([matrix for matrix in possible_tables if np.all(np.sum(matrix, axis=0)) and np.all(np.sum(matrix, axis=1)) and np.all(min(n_signals, n_states) < np.sum(matrix) < n_signals * n_states)])
    return true_tables + e


def pragmatic_listener(matrix, alpha, priors, costs, utility=True):
    """
    Description:
    This function calculates all the matrices following the RSA framework.

    Parameters:
    matrix (array): The language table.
    alpha (float): The alpha value for the pragmatic speaker.
    priors (array): The priors for the states.
    costs (array): The costs for the signals.
    """
    if priors is None:
        priors = np.ones(matrix.shape[1])/matrix.shape[1]

    if costs is None:
        costs = np.zeros(matrix.shape[0])

    def rownorm(mat):
        return (mat.T / mat.sum(axis=1)).T

    def safelog(vals):
        with np.errstate(divide='ignore'):
            return np.log(vals)

    literal_listener = rownorm(matrix * priors)

    if utility is True:
        utilities = alpha * (safelog(literal_listener.T) + costs)
        speaker = rownorm(np.exp(utilities))
    elif utility is False:
        utilities = literal_listener.T
        speaker = rownorm(utilities)
    
    pragmatic_listener = rownorm(speaker.T * priors)

    return literal_listener, speaker, pragmatic_listener


def normalized_weighted_random_increment(weights, count):
    """
    Description:
    This function generates datapoints based on the weights given and normalizes them. 
    The weights will be the rows in the language table of the pragmatic listener.
    With infinite datapoints, the average of the generated data will be the same as the weights.
    
    Parameters:
    weights (array): The weights to generate the data from.
    count (int): The amount of datapoints to generate.
    """
    if count == 0:
        return weights
    
    increments = np.zeros_like(weights, dtype=int)
    for row in range(weights.shape[0]):
        chosen_indices = np.random.choice(weights.shape[1], size=count, p=weights[row, :])
    
        for idx in chosen_indices:
            increments[row][idx] += 1
    
    return increments #/ count


def create_random_matrix_no_zero_rows_or_cols(shape, e):
    rows, cols = shape
    if rows == 0 or cols == 0:
        raise ValueError("Matrix dimensions must be greater than 0.")
    
    matrix = np.random.choice([0, 1], size=(rows, cols))
    
    for i in range(rows):
        if not matrix[i].any():
            matrix[i, random.randint(0, cols - 1)] = 1
    
    for j in range(cols):
        if not matrix[:, j].any():
            matrix[random.randint(0, rows - 1), j] = 1
    return matrix + e



def canonical_form(matrix):
    """
    Compute the canonical form of a matrix by generating all row and column permutations,
    considering transpositions and rotations.
    """
    rows, cols = matrix.shape
    candidates = []
    
    # Generate all row permutations
    row_perms = permutations(range(rows))
    for rp in row_perms:
        permuted_rows = matrix[list(rp), :]
        # Generate all column permutations for each row-permuted matrix
        col_perms = permutations(range(cols))
        for cp in col_perms:
            permuted = permuted_rows[:, list(cp)]
            candidates.append(permuted)
            candidates.append(permuted.T)  # Include the transposed version

    # Return the lexicographically smallest matrix as the canonical form
    return min(candidates, key=lambda x: x.tolist())

def remove_duplicate_structures(matrices):
    """
    Removes duplicate matrices that are structurally identical under row/column permutations
    or rotations.
    """
    seen = set()
    unique_matrices = []
    
    for matrix in matrices:
        form = canonical_form(matrix)
        form_tuple = tuple(map(tuple, form))  # Convert to hashable format
        if form_tuple not in seen:
            unique_matrices.append(matrix)
            seen.add(form_tuple)
    
    return np.array(unique_matrices)

def canonical_form_fast(matrix):
    """
    Compute the canonical form of a matrix.
    Instead of trying all permutations, sort rows/columns and consider rotations/transpositions.
    """
    rows, cols = matrix.shape
    candidates = []

    for _ in range(2):  # Original and transposed
        for _ in range(4):  # 0°, 90°, 180°, 270° rotations
            # Add lexicographically smallest row-sorted form
            candidates.append(tuple(map(tuple, np.sort(matrix, axis=0))))
            matrix = np.rot90(matrix)  # Rotate 90°
        matrix = matrix.T  # Transpose the matrix

    return min(candidates)

def remove_duplicate_structures_fast(matrices):
    """
    Removes duplicate matrices that are structurally identical under row/column permutations
    or rotations.
    """
    seen = set()
    unique_matrices = []
    
    for matrix in matrices:
        form = canonical_form_fast(matrix)
        if form not in seen:
            unique_matrices.append(matrix)
            seen.add(form)
    
    return np.array(unique_matrices)


def remove_useless_structures(matrices):    
    result = []
    for matrix in matrices:
        if not np.array_equal(pragmatic_listener(matrix, 2.7, None, None, True)[2], pragmatic_listener(matrix, 2.7, None, None, False)[2]):
            result.append(matrix)
    return np.array(result)


def plot_formula_dict(utility, datapoints, size, dictionary, index=6):
    items_lengths = [(str(key), len(value)) for key, value in dictionary.items()]
    items_lengths.sort(key=lambda x: x[1], reverse=True)

    items, lengths = zip(*items_lengths)
    total_length = sum(lengths)
    lengths = np.array(lengths) / total_length

    # add smaller formulas into one bar called 'other'
    if len(lengths) > index:
        other_length = sum(lengths[index:])
        items = list(items[:index]) + ["Other"]
        remaining_lengths = list(lengths[:index]) + [other_length]

        lengths = np.array(remaining_lengths) / sum(remaining_lengths)

    print(f'accuracy: {lengths[0]}')

    plt.title(f'Utility function: {utility} \n Datapoints: {datapoints} \n Size: {size}')
    plt.bar(items, lengths)
    plt.xticks(rotation=-90)
    plt.show()


def dynamic_replace_with_vars_sympy(formula):
    variable_counter = 0
    variable_names = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa']
    variable_mapping = {}

    def relu(x):
        return Max(0, x)

    def neg(x):
        return -x

    def get_new_variable():
        nonlocal variable_counter
        var_name = variable_names[variable_counter] if variable_counter < len(variable_names) else f'var{variable_counter}'
        variable_counter += 1
        return symbols(var_name)

    P_lit = symbols('P_lit', positive=True)

    expr = eval(formula, {'log': log, 'P_lit': P_lit, 'neg': neg, 'relu': relu, 'abs': abs, 'exp': exp})

    # Simplify the expression and expand logs
    simplified_expr = simplify(expand(expr))

    # Replace constants with variables
    def replace_constants(expr):
        if expr.is_Number:
            abs_value = abs(expr)
            if abs_value == 0:
                return Rational(0)
            if abs_value not in variable_mapping:
                variable_mapping[abs_value] = get_new_variable()
            transformed_constant = variable_mapping[abs_value]

            # Avoid invalid operations
            if abs_value != 0:
                multiplier = Rational(expr / abs_value)
            else:
                multiplier = 1  # Handle edge case
            return multiplier * transformed_constant
        elif expr.is_Atom:  # Leave atoms (like symbols) unchanged
            return expr
        else:
            args = [replace_constants(arg) for arg in expr.args]
            if expr.func == neg:
                return -args[0]
            elif expr.func == log:
                return log(args[0])
            elif expr.func == exp:
                return exp(args[0])
            elif expr.func == abs:
                return abs(args[0])
            elif expr.func == relu:
                return relu(args[0])
            else:
                return expr.func(*args)

    transformed_expr = replace_constants(simplified_expr)
    cleaned_expr = simplify(transformed_expr)

    return cleaned_expr, variable_mapping


def print_wrong_formulas(formulas_dict, utility):
    for formula in formulas_dict:
        if formula != utility:
            print(formula)
            for tuples in formulas_dict[formula]:
                print(tuples[0])
                print(np.round(tuples[1]))


def dump_formulas(formulas, filename):
    with open(filename + '.pkl', 'wb') as f:
        pickle.dump(formulas, f)

def test_matrices(datapoints=None, size=(3,3), e=1e-6, max_matrices=100, generated_matrices=300):
    formulas = defaultdict(list)
    n_signals, n_states = size
    
    if n_signals * n_states < 20:
        language_tables = create_language_tables(n_signals, n_states, 0)
    else:
        language_tables = [create_random_matrix_no_zero_rows_or_cols(size, 0) for _ in range(generated_matrices)]      

    if len(language_tables) * n_signals *  n_states < 5000:
        language_tables = remove_duplicate_structures(language_tables)
        language_tables = remove_useless_structures(language_tables) + e

    else:
        language_tables = remove_duplicate_structures_fast(language_tables)
        language_tables = remove_useless_structures(language_tables) + e

    mul = int(np.ceil(max_matrices/len(language_tables)))
    language_tables = np.tile(language_tables, (mul, 1, 1))
    language_tables = language_tables[:max_matrices]
    print(len(language_tables))


    model = PySRRegressor(
        niterations=20,
        binary_operators=["*", "+", "-"],
        unary_operators=["log", "exp", "abs", "relu", "neg"],
        loss_function=create_loss(n_signals, n_states),
        temp_equation_file="/home/lev/afstuderen/debug_log.txt",
        maxsize=7,
        #parsimony=0.01,
        )
    
    print(f"Testing {len(language_tables)} language tables")

    training = 0
    for language in language_tables:
        training += 1
        print(f'run {training} of {len(language_tables)}')
        
        literal_listener, _, listener = pragmatic_listener(language, 2.7, None, None)
        
        listener = normalized_weighted_random_increment(listener, datapoints)

        literal_listener = literal_listener.flatten().reshape(-1, 1)
        listener = listener.flatten().reshape(-1, 1)

        model.fit(literal_listener, listener, variable_names=['P_lit'])
        best = model.equations_['loss'].idxmin()
        formula = model.equations_['equation'][best]
        print(formula)
        formulas[str(dynamic_replace_with_vars_sympy(formula)[0])].append((str(formula), language))
        
    return formulas

In [5]:
def generate_and_dump_formulas(datapoints, size, max_matrices, generated_matrices, filename):
    formulas = test_matrices(datapoints=datapoints, size=size, max_matrices=max_matrices, generated_matrices=generated_matrices)
    dump_formulas(formulas, filename)


In [6]:
# output data format: datafram [signals, states, datapoints, predicted formula (score), predicted formula (loss), language table, literal listener, pragmatic listener, distrubed pragmatic listener, alpha, model_iterations]
import pandas as pd
from pysr import PySRRegressor

class SRonRSA:
    def __init__(self, datapoints, size, e, runs, filename, model_iterations, alpha=2.7):
        self.datapoints = datapoints
        self.size = size
        self.e = e
        self.runs = runs
        self.filename = filename
        self.model_iterations = model_iterations
        self.alpha = alpha
        self.output = pd.DataFrame(columns=['signals', 'states', 'datapoints','raw formula (score)', 'raw formula (loss)', 'predicted formula (score)', 'predicted formula (loss)', 'loss', 'alpha', 'model_iterations', 'language table', 'literal listener', 'pragmatic listener', 'distrubed pragmatic listener'])

    def create_matrices(self):
        n_signals, n_states = self.size

        if n_signals * n_states < 20:
            language_tables = create_language_tables(n_signals, n_states, 0)
        else:
            language_tables = [create_random_matrix_no_zero_rows_or_cols(self.size, 0) for _ in range(self.runs*2)]      

        if len(language_tables) * n_signals *  n_states < 5000:
            language_tables = remove_duplicate_structures(language_tables)
            language_tables = remove_useless_structures(language_tables) + self.e

        else:
            language_tables = remove_duplicate_structures_fast(language_tables)
            language_tables = remove_useless_structures(language_tables) + self.e

        mul = int(np.ceil(self.runs/len(language_tables)))
        language_tables = np.tile(language_tables, (mul, 1, 1))
        language_tables = language_tables[:self.runs]

        return language_tables

    def run(self):
        run = 0
        language_tables = self.create_matrices()

        for language in language_tables:
            run += 1
            print(f'run {run} of {len(language_tables)}')
            literal_listener, _, prag_listener = pragmatic_listener(language, self.alpha, None, None)

            distributed_listener = normalized_weighted_random_increment(prag_listener, self.datapoints)
            
            literal_listener = literal_listener.flatten().reshape(-1, 1)
            prag_listener = prag_listener.flatten().reshape(-1, 1)
            distributed_listener = distributed_listener.flatten().reshape(-1, 1)

            model = PySRRegressor(
                random_state=0,
                niterations=self.model_iterations,
                binary_operators=["*", "+", "-"],
                unary_operators=["log", "exp", "abs", "relu", "neg"],
                loss_function=create_loss(self.size[0], self.size[1]),
                temp_equation_file="/home/lev/afstuderen/debug_log.txt",
                maxsize=7,
                )

            model.fit(literal_listener, distributed_listener, variable_names=['P_lit'])
            best_loss = model.equations_['loss'].idxmin()
            best_score = model.equations_['score'].idxmax()
            raw_formula_loss = model.equations_['equation'][best_loss]
            formula_loss = dynamic_replace_with_vars_sympy(raw_formula_loss)[0]
            raw_formula_score = model.equations_['equation'][best_score]
            formula_score = dynamic_replace_with_vars_sympy(raw_formula_score)[0]
            loss = model.equations_['loss'][best_loss]


            new_row = pd.DataFrame({
                'signals': [self.size[0]], 
                'states': [self.size[1]], 
                'datapoints': [self.datapoints],
                'raw formula (score)': [str(raw_formula_score)],
                'raw formula (loss)': [str(raw_formula_loss)],
                'formula (score)': [str(formula_score)], 
                'formula (loss)': [str(formula_loss)], 
                'alpha': [self.alpha], 
                'model_iterations': [self.model_iterations], 
                'language table': [language.tobytes()], 
                'literal listener': [literal_listener.tobytes()], 
                'pragmatic listener': [prag_listener.tobytes()], 
                'distrubed pragmatic listener': [distributed_listener.tobytes()],
                'loss': [loss]
            })

            self.output = pd.concat([self.output, new_row], ignore_index=True)

        self.output.to_csv(self.filename + '.csv', index=False)


In [7]:

language = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 0]]) + 1e-6
literal_listener, _, prag_listener = pragmatic_listener(language, 2.7, None, None)
print(prag_listener)
print(normalized_weighted_random_increment(prag_listener, 100))


[[2.22293756e-01 3.88853122e-01 3.88853122e-01]
 [3.63732130e-01 4.01456802e-17 6.36267870e-01]
 [3.63732130e-01 6.36267870e-01 4.01456802e-17]]
[[23 39 38]
 [35  0 65]
 [38 62  0]]


In [54]:
def create_loss(signals, states, penalty=0):
    """
    Description: Create a custom loss function for the symbolic regression based on the number of signals and states.
    The function follows RSA's steps to turn a literal listener into a pragmatic speaker and then into a pragmatic listener, 
    while using the predicted formula as a utility function. 
    The loss function calculates the discrepancy using a multinomial loss.

    Parameters:
    signals: (int): Number of signals
    states: (int): Number of states
    """
    str1 = """function pragmatic_speaker_objective(tree, dataset::Dataset{T,L}, options) where {T,L}"""
    str2 = f"""
    # Matrix dimensions
    num_rows = {signals}
    num_cols = {states}
    matrix_size = num_rows * num_cols

    # Get predictions
    prediction, completion = eval_tree_array(tree, dataset.X, options)
    if !completion
        return L(Inf)  # Return a high loss if evaluation fails
    end

    # exp on the predictions
    prediction = exp.(prediction)

    # Normalize each column of the prediction matrix
    for j in 1:num_cols
        column = prediction[j:num_cols:end]
        
        column_sum = sum(column)
        normalized_column = column_sum != 0 ? column / column_sum : column

        prediction[j:num_cols:end] .= normalized_column
    end

    # Normalize each row of the prediction matrix
    for j in 1:num_rows
        row = prediction[(j-1)*num_cols+1:j*num_cols]
        
        row_sum = sum(row)
        normalized_row = row_sum != 0 ? row / row_sum : row

        prediction[(j-1)*num_cols+1:j*num_cols] .= normalized_row
    end

    # Calculate the loss for each row and add it to the total loss
    total_loss = 0.0
    for i in 1:num_cols:length(prediction)
        row_start = i
        row_end = row_start + num_cols - 1

        predicted_row = prediction[row_start:row_end]
        target_row = dataset.y[row_start:row_end]
        
        # Multinomial loss for the row
        row_loss = -sum(target_row .* log.(predicted_row))
        total_loss += row_loss
    end
    complexity = count_nodes(tree)
    return (total_loss / num_rows) * {1+penalty}^complexity
end
"""
    return str1+str2

In [71]:

language = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 0]]) + 1e-6
literal_listener2, _, prag_listener2 = pragmatic_listener(language, 1, None, None)
print(np.round(prag_listener2, 2))
literal_listener, _, prag_listener = pragmatic_listener(language, 2.7, None, None)
print(np.round(prag_listener,2))

output = normalized_weighted_random_increment(prag_listener, 100)


model = PySRRegressor(
    niterations=20,
    binary_operators=["*", "+", "-"],
    unary_operators=["log", "exp", "abs", "relu", "neg"],
    loss_function=create_loss(3, 3),
    temp_equation_file="/home/lev/afstuderen/debug_log.txt",
    maxsize=7,
    )

literal_listener = literal_listener.flatten().reshape(-1, 1)
output = output.flatten().reshape(-1, 1)

model.fit(literal_listener, output, variable_names=['P_lit'])

[[0.24 0.38 0.38]
 [0.38 0.   0.62]
 [0.38 0.62 0.  ]]
[[0.22 0.39 0.39]
 [0.36 0.   0.64]
 [0.36 0.64 0.  ]]


[ Info: Started!


PySRRegressor.equations_ = [
	   pick         score                          equation       loss  complexity
	0        0.000000e+00                             P_lit  99.944720           1
	1  >>>>  2.318411e-01                        log(P_lit)  79.263374           2
	2        3.403159e-04                 P_lit * 15.259014  79.236404           3
	3        1.133379e-03            log(P_lit) * 3.0690436  79.146650           4
	4        3.158693e-08  (log(P_lit) - P_lit) * 5.2169886  79.146645           6
]

In [ ]:
penalties = [0.1**x for x in np.arange(0, 9)]
for penalty in penalties:
    output = pd.DataFrame(columns=['signals', 'states', 'datapoints','raw formula (score)', 'raw formula (loss)', 'loss', 'alpha', 'model_iterations', 'language table', 'literal listener', 'pragmatic listener', 'distrubed pragmatic listener'])
    model = PySRRegressor(
        random_state=0,
        niterations=20,
        binary_operators=["*", "+", "-"],
        unary_operators=["log", "exp", "abs", "relu", "neg"],
        loss_function=create_loss(3, 3, penalty),
        temp_equation_file="/home/lev/afstuderen/debug_log.txt",
        maxsize=7,
        )
    language = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 0]]) + 1e-6
    for i in range(50):
        literal_listener, _, prag_listener = pragmatic_listener(language, 2.7, None, None)
        distributed_listener = normalized_weighted_random_increment(prag_listener, 100)
        literal_listener = literal_listener.flatten().reshape(-1, 1)
        distributed_listener = distributed_listener.flatten().reshape(-1, 1)
        model.fit(literal_listener, distributed_listener, variable_names=['P_lit'])
        best_loss = model.equations_['loss'].idxmin()
        best_score = model.equations_['score'].idxmax()
        raw_formula_loss = model.equations_['equation'][best_loss]
        formula_loss = dynamic_replace_with_vars_sympy(raw_formula_loss)[0]
        raw_formula_score = model.equations_['equation'][best_score]
        formula_score = dynamic_replace_with_vars_sympy(raw_formula_score)[0]
        loss = model.equations_['loss'][best_loss]

        new_row = pd.DataFrame({
            'signals': [3], 
            'states': [3], 
            'datapoints': [100],
            'raw formula (score)': [str(raw_formula_score)],
            'raw formula (loss)': [str(raw_formula_loss)],
            'formula (score)': [str(formula_score)], 
            'formula (loss)': [str(formula_loss)], 
            'alpha': [2.7], 
            'model_iterations': [20], 
            'language table': [language.tobytes()], 
            'literal listener': [literal_listener.tobytes()], 
            'pragmatic listener': [prag_listener.tobytes()], 
            'distrubed pragmatic listener': [distributed_listener.tobytes()],
            'loss': [loss]
        })

        output = pd.concat([output, new_row], ignore_index=True)
    output.to_csv(f'penalty={penalty}.csv', index=False)
    
    
    
    

[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
[ Info: Started!
